### ISSUE TITLE
whenever

### ISSUE THREAD

**Issue by liren-sun** [the-teacher/rails7-startkit#2]
why not use sidekiq-cron?

**Comment by the-teacher** [comment]
Hi @liren-sun!
Thank you for your message!

Many on my personal preferences match to winners in related categories on ruby toolbox.
Also I would like to have some diversity in technologies because this project is kind of an educational things.

<img width="496" alt="Screenshot 2023-01-13 at 00 06 23" src="https://user-images.githubusercontent.com/496713/212181289-de337923-7be7-49c7-a31d-adae1e13908e.png">

Anyway I'm ready see nice PR to this project to make it interesting and helpful.
If you have something, please send your code. I'll be really happy!

Thank you!
