### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by MtnBiker** [the-teacher/rails7-startkit#48]
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rails 7. StartKit
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> Docker not running
To continue please run Docker
```

========

```
➜ ruby -v
ruby 3.1.2p20
Not 3.2.2 because this MBA won't let puma launch.. But you didn't specify a Ruby version.

Gemfile does show 3.2.1. Also gem "rails", "7.0.7.2" which probably should be updated.
````

**Comment by the-teacher** [comment]
`Is the docker daemon running?`

- https://www.docker.com/

@MtnBiker please install and run docker and try again

**Comment by the-teacher** [comment]
@MtnBiker 
This video shows how it should work https://www.youtube.com/watch?v=f6aAwAMH4Q8

**Comment by MtnBiker** [comment]
Afraid I don’t usually interact with Docker directly

➜ docker ps --all
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by the-teacher** [comment]
Hi @MtnBiker 

You have done a great job! Everything goes well and you are close to solve the case with docker

### Option 1
Please try to find docker icon on your computer and click it and run. 

<img width="110" alt="Screenshot 2023-10-08 at 08 41 19" src="https://github.com/the-teacher/rails7-startkit/assets/496713/e9762778-2667-4db7-a3e2-6c375fc7b468">

Usually it should run Docker UI and start Docker service.

<img width="883" alt="Screenshot 2023-10-08 at 08 41 07" src="https://github.com/the-teacher/rails7-startkit/assets/496713/0c4c8748-c1c4-4061-87d0-1190bd902cae">

### Option 2

IF for a reason you can not find the icon - there is a documentation how to run service from the terminal window.

https://docs.docker.com/config/daemon/start/

@MtnBiker Please keep me informed about your situation.

**Comment by the-teacher** [comment]
@MtnBiker 

Also you should be careful with typing

🛑  Not `./bin exec restart_all`

🟢  `bin/exec resatrt_all` or  (mostly for windows) `ruby bin/exec resatrt_all`

**Comment by MtnBiker** [comment]
No reason why I would have what from your description is an App named Docker. And doesn’t appear in search.

The second recommendation requires sudo which is something that someone that needs a startkit shouldn’t be using.

But thanks for your efforts. I would think it will be hard to do because of a variety of setups.

**Comment by the-teacher** [comment]
Hello @MtnBiker !

1. from your messages I saw that you already have docker: `Docker version 24.0.6, build ed223bc820`
2. Docker was not started `Cannot connect to the Docker daemon`

Docker is very popular tool and since Rails release `7.1` even is a default tool for Rails.
The only problem you had -  Docker was not started on your computer. I'm sorry that you didn't find a way to launch it.

3. `second recommendation requires sudo` I'm sure no. Command `bin/exec` or `ruby bin/exec` runs a simple  ruby script. There is not need to use `sudo`. Please, check file permissions on your computer, from the root of the project `ls -al ./bin`

If you need any help please let me know
